---
title: "Difference-in-Differences for Social Epidemiology"
subtitle: "Danish Epidemiology Society Workshop"
author: "Sam Harper"
date: 2024-11-06
date-format: iso
format: html
bibliography: des.bib
csl: vancouver.csl
---
```{r ignore, include=FALSE, eval=FALSE}
## Introduction

At the same time as social epidemiology started to articulate a new vision for place-based and contextual effects to bring back the focus on population health, the formal literature on causal inference as applied to epidemiology was also taking shape. Foundational work by Robins, Greenland, Pearl, Hernan and others in the mid-to-late 1990s. 

In discussing the disappointing results of community-based trials such as COMMIT, Syme remarks on another key idea that helped to motivate a focus on multilevel thinking in social epidemiology:

> If our goal is to prevent disease and promote health, I don't think we can accomplish it by focusing exclusively on individual diseases and risk factors.

Syme covers some of the same ground nearly a decade earlier in a special issue of Daedalus (1994), arguing that a focus on individual-level risk factors is unlikely to be helpful for improving disease, with some evidence from failed trials such as MRFIT to support his view. He also is highly enthusiastic about the recent work of Marmot, specifically regarding the social class "gradient" that exists and can't be explained by traditional risk factors.  

McKinley and Marceau (Lancet 2000):

> The limitations of the risk factor paradigm12, 13 and disappointing results from community-intervention trials aimed at their reduction14, 15 have encouraged researchers to refocus “upstream”16 on the real or underlying reasons for the social patterns of disease.17

McKinley and Marceau (AJPH 1999):

> There are signs of a shift in focus from people to place to social position, which mirrors the different levels of causality behind complex human behavior.


In their historical discussion of the work of Mervyn Susser, Kaufman and Poole [@kaufman2000] identify the tension between pragmatic notions of causal inference present in much of social epidemiologic literature and the formal counterfactual models of causal inference from the statistics literature. 

What about [@merlo2003]?

As Pearce [@pearce1996] noted, much of the problem with 'traditional epidemiology' was its insistence that socioeconomic factors were not 'real' causes of illness.

Impossible to ignore the role that the studies assessing the potential impact of income inequality on health had on the neighborhood effects literature. This was a 'big idea' per the editors of the BMJ. 

Arcaya et al. [@arcaya2016] conducted an innovative systematic review of the *characteristics* of multi-level studies of neighborhood effects. They restricted to studies that used multi-level modeling


In many respects this was already an exciting time for social epidemiology. Although the roots of social epidemiology trace back to the earliest beginnings of public health and social medicine, emphasis on social factors as causes of disease has ebbed and flowed over the course of the last few centuries. However, during early-to-mid 1990s we witnessed a flood of disciplinary critiques
```


The theme for this conference is "Methods to study social inequality in health". This is a broad subject and there are, in fact, many ways to unpack this theme. What kinds of tools do we need to 'study' social inequality in health? Well, we have to think about several.

First, we have to understand something about what we mean by the terms 'social' and 'inequality'. You've just spent the morning learning all about how to actually conceptualize and measure the 'social' in 'social inequalities', so I'm not going to spend much time on that. 

A second key concept here is the 'inequality' part of 'social inequality'. We could spend a lot of time talking about what we mean by 'inequality', as well as the different ways we may want to measure it, but for the purposes of this talk I'm going to focus mostly on differences in health status between social groups. 

I will be discussing the difference-in-differences (DiD) method, which is a quasi-experimental design that is widely used in social epidemiology.